config/routes.rb
Rails.application.routes.draw do
  get 'public_recipes/index'
  devise_for :users, sign_out_via: [:get, :post]
  resources :foods 
  resources :users, only: [:index]
  resources :recipes do
    resources :recipe_foods
  end

  get '/general_shopping_list', to: 'foods#general'
  resources :public_recipes

  root to: "foods#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  before_create :set_recipe_number

  attr_accessor :recipe_sequence_number

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 50 }
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :public, inclusion: { in: [true, false] }

  def recipe_number
    user_recipes = Recipe.where(user_id:)
    user_recipes.index(self) + 1
  end

  def set_recipe_number
    self.recipe_sequence_number = (Recipe.last.try(:recipe_sequence_number) || 0) + 1
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id).order(created_at: :desc)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    recipe_test = Recipe.find(params[:id])
    unless recipe_test.user == current_user || recipe_test.public?
      flash[:alert] =
        'You do not have access to see details.'
      return redirect_to recipes_path
    end

    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    @recipe.public = params.fetch(:recipe, {}).fetch(:public, false) == 'true'

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.js
      else
        format.html { render :new, alert: 'An error has occurred while creating the recipt, try again' }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      if @recipe.destroy
        format.html { redirect_to recipes_path, notice: 'Recipe was deleted successfully.' }
      else
        format.html { render :new, alert: 'An error has occurred while deleting the recipt, try again' }
      end
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/views/recipes/_form.html.erb
<section class="flex-column">
  <div class="newRecepForm">
    <%= form_with model: @recipe do |form| %>
    <h2>Welcome little <%= current_user.name %>, please add your recipe</h2>
    <div class="form-locaton">
      <%= form.text_field :name, placeholder: "Title", class:'form-control' %>
    </div>
    
    <div class="form-locaton">
        <%= form.number_field :preparation_time, placeholder: "Preparation time in min", class:'form-control' %>
    </div>
    
    <div class="form-locaton">
        <%= form.number_field :cooking_time, placeholder: "Cooking time in min", class:'form-control' %>
      </div>
    
    <div class="form-locaton">
        <%= form.text_area :description, required: true, placeholder: "Description", class:'form-control'%>
    </div>
    
    <div class="form-locaton check-box">
      <%= form.label :public, class: "form-label-checkbox"%>
      <%= form.check_box :public, {}, 'true', 'false' %>
    </div>
    
    <div class="form-locaton">
        <%= form.submit "Add", class:'add-recipe-btn' %>
    </div>
    
    <% end %>
  </div>
</section>

app/views/recipes/_ingredian.html.erb
<tbody>
  <tr class="">
    <td class="">
      <div class="">
        <div class="">
          <div class=""><%= recipe_food.food.name%></div>
        </div>
      </div>
    </td>
    <td class="">
      <%= recipe_food.quantity %>
    </td>
    <td class="">
      <%= recipe_food.quantity * recipe_food.food.price %>
    </td>
    <td class=" ">
      <span class="">
        <i class=""><%= button_to "Delete ingredient", "#{recipe_recipe_foods_path(@recipe)}/#{recipe_food.id}", method: :delete, data: { confirm: "Are you sure?" } %></i>
        </span>
    </td>
    <td>
    <td>
    <td>
    <td>
  </tr>
</tbody>

app/views/recipes/_recipe.html.erb
<li class="recipe-listing">
  <div class="recipe-name">
    <%= link_to recipe_path(recipe) do %>
     <h4>Recipe #<%= recipe.recipe_number %> </h4>
     <p><%= recipe.name %></p>
    <% end %>
    <% if current_user.id == recipe.user_id%>
      <div>
          <%= button_to "Remove", recipe_path(recipe), :method => :delete, data: {turbo_method: :delete}, class: "delete-button" %>
      </div>
    <% end %>
  </div>
  <div class="recipe-description">
    <%=recipe.description%>
  </div>
</li>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

app/views/recipes/index.html.erb
 <div>
 <h1 class="heading">Recipes</h1>
    <div class="add-btn-container" >
      <%= link_to "New recipe", new_recipe_path, class: "add-btn" %>
    </div>
    <div class="recipes-container flex-column">
      <% @recipes.each do |recipe| %>
        <%= render recipe %>
      <% end %>
    </div>
</div>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<link
	href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
	rel="stylesheet">
<div class="recipe-details">
  <h1 class="recipe-name-show">Recipe <%= @recipe.recipe_number %></h1>
  <div class="recipe-info">
    <div class="info-item">
      <h2> <%= @recipe.description %></h2>
    </div>
    <div class="info-item flex-around">
      <p><b>Preparation Time:  <span> <%= @recipe.preparation_time %></span></b></p>
    </div>
    <div class="info-item">
      <p><b>Cooking Time: <span> <%= @recipe.cooking_time %></span></b></p>      
    </div>
    <% if @current_user.id == @recipe.user_id %>
      <div class="info-item public-switch">
        <span>Public</span>
        <label for="public-switch">
          <input type="checkbox" id="public-switch" class="" <%= @recipe.public ? 'checked' : '' %>>
          <div class="switch"></div>
        </label>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <div class="action-item">
      <%= link_to "/general_shopping_list", class: "action-link" do %>
        <button class="add-food-btn">
          General Shopping List
        </button>
      <% end %>
    </div>
    <div class="action-item">
      <%= link_to new_recipe_recipe_food_path(@recipe), class: "action-link" do %>
        <button class="add-food-btn">
          Add Ingredient
        </button>
      <% end %>
    </div>
  </div>
</div>
    
     <hr class="">
		<div class="ingredient-container">
			<table class="food-table">
        <% if @recipe_foods.length > 0 %>
        <thead class="table-header">
          <tr>
            <th class="table-header-cell">Food</th>
            <th class="table-header-cell">Quantity</th>
            <th class="table-header-cell">Value</th>
            <th class="table-header-cell">Actions</th>
          </tr>
        </thead>
        
          <% @recipe_foods.each do |recipe_food| %>
            <%= render :partial => 'recipe_foods/recipe_ingredients', :locals => {:recipe_food => recipe_food} %>
          <% end %>
    <% else %>
      <p class="">Ingredient list is empty.</p>
    <% end %>
        </table>
                </div>
	</div>
</div>

<style>
	.table {
		border-spacing: 0 15px;
	}

	i {
		font-size: 1rem !important;
	}

	.table tr {
		border-radius: 20px;
	}

	tr td:nth-child(n+5),
	tr th:nth-child(n+5) {
		border-radius: 0 .625rem .625rem 0;
	}

	tr td:nth-child(1),
	tr th:nth-child(1) {
		border-radius: .625rem 0 0 .625rem;
	}
</style>