config/routes.rb
Rails.application.routes.draw do
  get 'public_recipes/index'
  devise_for :users, sign_out_via: [:get, :post]
  resources :foods 
  resources :users, only: [:index]
  resources :recipes do
    resources :recipe_foods
  end

  get '/general_shopping_list', to: 'foods#general'
  resources :public_recipes

  root to: "foods#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 50 }
  validates :measurement, presence: true, length: { maximum: 20 }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    # N + 1 optimization
    @foods = current_user.foods.includes(:user)
  end

  def new
    @food = Food.new
  end

  def create
    food = current_user.foods.new(food_params)

    if food.save
      redirect_to foods_path, notice: 'New Food was successfully added.'
    else
      flash[:alert] = 'New Food adding Failed. Please try again.'
    end
  end

  def edit
    @food = current_user.foods.find(params[:id])
  end

  def update
    @food = current_user.foods.find(params[:id])
    if @food.update(food_params)
      redirect_to foods_path, notice: 'Food was successfully updated.'
    else
      flash[:alert] = 'Food updating Failed. Please try again.'
    end
  end

  def destroy
    food = Food.find(params[:id])

    unless food.user == current_user
      return flash[:alert] =
               'You do not have access to delete the Food belongs to other Users.'
    end

    if food.destroy
      flash[:notice] = 'Food was successfully deleted.'
    else
      flash[:alert] = 'Food deleting Failed. Please try again.'
    end
    redirect_back(fallback_location: root_path)
  end

  def general
    # N + 1 optimization
    @foods = current_user.foods.includes([:recipe_foods])
    current_user.recipes.map do |recipe|
      recipe.recipe_foods.map do |recipe_food|
        food = recipe_food.food
        test = @foods.select { |f| f.name == food.name }[0]
        test.quantity = test.quantity - recipe_food.quantity
      end
    end
    @foods = @foods.select { |f| f.quantity.negative? }
    @foods.each { |f| f.quantity *= -1 }
    @total = 0
    @foods.each do |food|
      @total += (food.price * food.quantity)
    end
  end

  def food_params
    params.require(:food).permit(:name, :quantity, :measurement, :price)
  end
end

app/views/foods/_food.html.erb
<tbody>
					<tr class="">
						<td class="">
							<div class="">
								<div class="">
									<div class=""><%= food.name%></div>
								</div>
							</div>
						</td>
						<td class="">
							<%= food.quantity %>
						</td>
						<td class="">
							<%= food.measurement %>
						</td>
						<td class="">
							<span class="">$ <%= food.price %></span>
						</td>
						<td class=" ">

							<span class="">
								<i class=""><%= button_to "Delete", food_path(food.id), method: :delete, data: { confirm: "Are you sure?" }, class:"delete-button" %></i>
						    </span>
						</td>
					</tr>
				</tbody>
        

app/views/foods/_form.html.erb
<div class="form-container">
  <%= form_with model: @food, class: "form-input" do |form| %>
    <div class="form-group">
      <%= form.label :name, "Name", class: "form-label" %>
      <%= form.text_field :name, placeholder: "Name", required: true, autofocus: true, class: "form-input" %>
    </div>
    <div class="form-group">
      <%= form.label :quantity, "Quantity", class: "form-label" %>
      <%= form.number_field :quantity, placeholder: 0, required: true, autofocus: true, class: "form-input" %>
    </div>
    <div class="form-group">
      <%= form.label :measurement, "", class: "form-label" %>
      <%= form.text_field :measurement, placeholder: "kg", required: true, autofocus: true, class: "form-input" %>
    </div>
    <div class="form-group">
      <%= form.label :price, "Price", class: "form-label" %>
      <%= form.number_field :price, placeholder: 100, required: true, autofocus: true, class: "form-input" %>
    </div>
    <div class="form-group">
      <%= form.submit "Add Food", data: { disable_with: "Loading" }, class: "form-submit" %>
    </div>
  <% end %>
</div>

app/views/foods/edit.html.erb
<div class="">
  <div class="">
    <div class="">
      <div class="">
        <h1 class="">Edit Your Food</h1>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/foods/general.html.erb
<div class="List">
  <h1 class="heading">Shopping List</h1>
  <div class="shopping-info">
    <div><span class="">Amount of food items to buy : </span><span class="">&nbsp;<%= @foods.length %></span></div>
      <div><span class="">Total value of food needed:</span><span class="">&nbsp;$<%= @total %></span></div>
  </div>
  <table id="general-table">
    <thead>
      <tr>
        <th class="">Food</th>
        <th class="">Quantity</th>
          <th class="">Price</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr class="">
          <td class=""><%= food.name %></td>
            <td class=""><%= food.quantity %></td>
          <td class="">$<%= food.price * food.quantity %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/index.html.erb
<div class="container">
	<div class="row">
		<div class="add-btn-container">
			<%= link_to "Add Food", new_food_path, class: "add-food-btn" %>
		</div>
		<div class="col-12">
			<table class="food-table">
				<thead class="table-header">
					<tr>
						<th class="table-header-cell">Food</th>
						<th class="table-header-cell">Initial Quantity</th>
						<th class="table-header-cell">Measure</th>
						<th class="table-header-cell">Unit Price</th>
						<th class="table-header-cell">Action</th>
					</tr>
				</thead>
				<% @foods.each do |food|%>
				<%= render 'food', food: food %>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/foods/new.html.erb
<div class="">
	<div class="">
		<div class="">
			<div class="">
				<div>
					<h1 class="">Add Your Food</h1>
                     <% if @food.errors.any? %>
                            <ul>
                            <% @food.errors.full_messages.each do |msg|%>
                            <li><%= msg %></li>
                            <% end %>
                            </ul>
                    <% end %>

				</div>
				<%= render 'form' %>
            </div>
        </div>
    </div>
</div>