config/routes.rb
Rails.application.routes.draw do
  get 'public_recipes/index'
  devise_for :users, sign_out_via: [:get, :post]
  resources :foods 
  resources :users, only: [:index]
  resources :recipes do
    resources :recipe_foods
  end

  get '/general_shopping_list', to: 'foods#general'
  resources :public_recipes

  root to: "foods#index"
end

app/views/layouts/_nav.html.erb
<div class="navbar">
  <!-- navbar -->
  <nav>
    <div class="">
      <a href="/public_recipes" class="home-link">
        Recipe Inventory
      </a>
      <% if current_user %>
        <!-- Header Icons -->
        <div>
          <ul>
            <li><a href="/foods">Welcome <%= current_user.name %>!</a></li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>
  <ul>
    <li><%= link_to "Foods", foods_path, class: "navigation-link" %></li>
    <li><%= link_to "Shopping List", "/general_shopping_list", class: "navigation-link" %></li>
    <!-- Nav Links -->
    <% if current_user %>
      <li><%= link_to "Recipes", recipes_path, class: "navigation-link" %></li>
      <li><%= link_to "Public Recipes", public_recipes_path, class: "navigation-link" %></li>
      <li><%= link_to 'Log out', destroy_user_session_path, method: :delete , data: { turbo: false }, class: "navigation-link log-out-link" %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeInventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script>
    </script>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </body>
</html>